### PR TITLE
Enum for picture notification

### PR DESCRIPTION
**Pull request by MaZyGer**
Let us make easier for developer if they us picture notification. Enums are safer than strings that can be incorrectly written. Everything is tested and they are working.

### CODE REVIEW

**Comment by Guad** [comment]
There are much more NotificationPicType than you wrote. There needs to be an option for a custom one, via string.

**Comment by MaZyGer** [comment]
Oh I just looked here: http://www.dev-c.com/nativedb/func/info/1ccd9a37359072cf .  There are only three. How many are there really? I or we can add them too.

**Comment by Guad** [comment]
Every texture dict in x64b.rpf/data/cdimages/scaleform_generic.rpf that starts with char_. There are 168

**Comment by MaZyGer** [comment]
Uff there are way to many hehe. 

Well we can pick some important pics there and make overload function to allow custom string too if you allow. I took this list now
http://gtaforums.com/topic/821783-v-pc-notification-pictures/

If not I will reset to default. How is about NotificationIconType?

**Comment by Guad** [comment]
All is fine now, thank you!

**Pull request merged**
